/**
 * ZionX Studio — World-Class Branding Library
 *
 * 50 premium branding styles inspired by real-world apps and design systems.
 * Each style includes complete design tokens for colors, typography, spacing,
 * and visual properties that can be applied instantly to any app.
 *
 * Categories: wellness, productivity, finance, social, entertainment,
 * education, health, lifestyle, business, creative
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type BrandingCategory =
  | 'wellness'
  | 'productivity'
  | 'finance'
  | 'social'
  | 'entertainment'
  | 'education'
  | 'health'
  | 'lifestyle'
  | 'business'
  | 'creative';

export interface BrandingStyle {
  id: string;
  name: string;
  category: BrandingCategory;
  description: string;
  inspiration: string;
  tags: string[];

  colors: {
    primary: string;
    secondary: string;
    accent: string;
    background: string;
    surface: string;
    text: string;
    textSecondary: string;
    success: string;
    warning: string;
    error: string;
  };

  typography: {
    headingFont: string;
    bodyFont: string;
    monoFont: string;
    scale: 'compact' | 'default' | 'spacious';
  };

  borderRadius: 'none' | 'subtle' | 'rounded' | 'pill';
  shadowStyle: 'none' | 'subtle' | 'elevated' | 'dramatic';
  animationStyle: 'none' | 'subtle' | 'smooth' | 'playful' | 'dramatic';
  density: 'compact' | 'comfortable' | 'spacious';
  mode: 'light' | 'dark' | 'auto';

  previewGradient: string;
}

// ---------------------------------------------------------------------------
// Category Metadata
// ---------------------------------------------------------------------------

export const BRANDING_CATEGORIES: { id: BrandingCategory; label: string; icon: string; description: string }[] = [
  { id: 'wellness', label: 'Wellness', icon: '🧘', description: 'Calm, mindful, and restorative' },
  { id: 'productivity', label: 'Productivity', icon: '⚡', description: 'Focused, efficient, and clean' },
  { id: 'finance', label: 'Finance', icon: '💰', description: 'Trustworthy, data-rich, and precise' },
  { id: 'social', label: 'Social', icon: '💬', description: 'Connected, expressive, and vibrant' },
  { id: 'entertainment', label: 'Entertainment', icon: '🎬', description: 'Immersive, bold, and engaging' },
  { id: 'education', label: 'Education', icon: '📚', description: 'Accessible, structured, and motivating' },
  { id: 'health', label: 'Health & Fitness', icon: '🏋️', description: 'Energetic, data-forward, and motivational' },
  { id: 'lifestyle', label: 'Lifestyle', icon: '✨', description: 'Warm, visual, and aspirational' },
  { id: 'business', label: 'Business', icon: '💼', description: 'Professional, collaborative, and scalable' },
  { id: 'creative', label: 'Creative', icon: '🎨', description: 'Expressive, bold, and artistic' },
];

// ---------------------------------------------------------------------------
// 50 Branding Styles
// ---------------------------------------------------------------------------

export const BRANDING_STYLES: BrandingStyle[] = [
  // ===========================================================================
  // WELLNESS (6 styles)
  // ===========================================================================

  {
    id: 'calm-serenity',
    name: 'Calm Serenity',
    category: 'wellness',
    description: 'Deep navy paired with soft gold accents. Serif headings evoke tranquility with spacious layouts and dramatic shadows that create depth.',
    inspiration: 'Calm app',
    tags: ['dark', 'serif', 'luxury', 'meditation', 'sleep'],
    colors: {
      primary: '#2C3E6B',
      secondary: '#1A2744',
      accent: '#D4AF37',
      background: '#0F1B33',
      surface: '#1A2744',
      text: '#F5F0E8',
      textSecondary: '#A8B4C8',
      success: '#4ADE80',
      warning: '#FBBF24',
      error: '#F87171',
    },
    typography: {
      headingFont: 'Playfair Display',
      bodyFont: 'Source Sans Pro',
      monoFont: 'JetBrains Mono',
      scale: 'spacious',
    },
    borderRadius: 'rounded',
    shadowStyle: 'dramatic',
    animationStyle: 'smooth',
    density: 'spacious',
    mode: 'dark',
    previewGradient: 'linear-gradient(135deg, #0F1B33 0%, #2C3E6B 50%, #D4AF37 100%)',
  },

  {
    id: 'headspace-playful',
    name: 'Headspace Playful',
    category: 'wellness',
    description: 'Warm orange tones with illustrated character style. Everything is rounded and friendly with playful bounce animations.',
    inspiration: 'Headspace',
    tags: ['warm', 'playful', 'illustrated', 'friendly', 'rounded'],
    colors: {
      primary: '#F47D31',
      secondary: '#FDB813',
      accent: '#FF6B35',
      background: '#FFF8F0',
      surface: '#FFFFFF',
      text: '#2D2D2D',
      textSecondary: '#6B6B6B',
      success: '#4CAF50',
      warning: '#FF9800',
      error: '#E53935',
    },
    typography: {
      headingFont: 'Poppins',
      bodyFont: 'Nunito',
      monoFont: 'Fira Code',
      scale: 'default',
    },
    borderRadius: 'rounded',
    shadowStyle: 'subtle',
    animationStyle: 'playful',
    density: 'comfortable',
    mode: 'light',
    previewGradient: 'linear-gradient(135deg, #FFF8F0 0%, #F47D31 50%, #FDB813 100%)',
  },

  {
    id: 'zen-garden',
    name: 'Zen Garden',
    category: 'wellness',
    description: 'Japanese minimalism with muted greens and cream. Generous whitespace, asymmetric layouts, and subtle ink-wash animations.',
    inspiration: 'Japanese zen aesthetics',
    tags: ['minimal', 'japanese', 'muted', 'whitespace', 'serene'],
    colors: {
      primary: '#5B7A5E',
      secondary: '#8B9E7C',
      accent: '#C4956A',
      background: '#F7F4F0',
      surface: '#FFFDF9',
      text: '#2C2420',
      textSecondary: '#7A6B5E',
      success: '#6B8F5E',
      warning: '#C4956A',
      error: '#B85450',
    },
    typography: {
      headingFont: 'Noto Serif',
      bodyFont: 'Noto Sans',
      monoFont: 'Noto Sans Mono',
      scale: 'spacious',
    },
    borderRadius: 'subtle',
    shadowStyle: 'none',
    animationStyle: 'subtle',
    density: 'spacious',
    mode: 'light',
    previewGradient: 'linear-gradient(135deg, #F7F4F0 0%, #8B9E7C 50%, #5B7A5E 100%)',
  },

  {
    id: 'ocean-breath',
    name: 'Ocean Breath',
    category: 'wellness',
    description: 'Teal gradients flowing into white. Organic wave shapes, smooth transitions, and a sense of endless calm like the sea.',
    inspiration: 'Ocean meditation apps',
    tags: ['teal', 'gradient', 'organic', 'flowing', 'calm'],
    colors: {
      primary: '#0D9488',
      secondary: '#06B6D4',
      accent: '#2DD4BF',
      background: '#F0FDFA',
      surface: '#FFFFFF',
      text: '#134E4A',
      textSecondary: '#5EEAD4',
      success: '#34D399',
      warning: '#FBBF24',
      error: '#FB7185',
    },
    typography: {
      headingFont: 'DM Sans',
      bodyFont: 'DM Sans',
      monoFont: 'DM Mono',
      scale: 'default',
    },
    borderRadius: 'rounded',
    shadowStyle: 'subtle',
    animationStyle: 'smooth',
    density: 'comfortable',
    mode: 'light',
    previewGradient: 'linear-gradient(135deg, #F0FDFA 0%, #0D9488 50%, #06B6D4 100%)',
  },

  {
    id: 'sunset-meditation',
    name: 'Sunset Meditation',
    category: 'wellness',
    description: 'Warm peach and coral gradients that evoke golden hour. Soft rounded corners and gentle fade animations throughout.',
    inspiration: 'Sunset/golden hour aesthetics',
    tags: ['warm', 'peach', 'coral', 'gradient', 'gentle'],
    colors: {
      primary: '#F97066',
      secondary: '#FDBA74',
      accent: '#FB923C',
      background: '#FFF7ED',
      surface: '#FFFFFF',
      text: '#431407',
      textSecondary: '#9A3412',
      success: '#4ADE80',
      warning: '#FBBF24',
      error: '#EF4444',
    },
    typography: {
      headingFont: 'Lora',
      bodyFont: 'Inter',
      monoFont: 'Fira Code',
      scale: 'default',
    },
    borderRadius: 'rounded',
    shadowStyle: 'subtle',
    animationStyle: 'smooth',
    density: 'comfortable',
    mode: 'light',
    previewGradient: 'linear-gradient(135deg, #FFF7ED 0%, #F97066 50%, #FDBA74 100%)',
  },

  {
    id: 'forest-therapy',
    name: 'Forest Therapy',
    category: 'wellness',
    description: 'Deep greens and earth tones inspired by forest bathing. Natural textures, grounding feel, and organic shapes throughout.',
    inspiration: 'Forest bathing / Shinrin-yoku',
    tags: ['green', 'earthy', 'natural', 'grounding', 'organic'],
    colors: {
      primary: '#166534',
      secondary: '#4D7C0F',
      accent: '#A16207',
      background: '#F5F2EB',
      surface: '#FEFDFB',
      text: '#1A1A1A',
      textSecondary: '#5C5C4A',
      success: '#22C55E',
      warning: '#EAB308',
      error: '#DC2626',
    },
    typography: {
      headingFont: 'Lora',
      bodyFont: 'Open Sans',
      monoFont: 'Source Code Pro',
      scale: 'spacious',
    },
    borderRadius: 'rounded',
    shadowStyle: 'subtle',
    animationStyle: 'subtle',
    density: 'spacious',
    mode: 'light',
    previewGradient: 'linear-gradient(135deg, #F5F2EB 0%, #166534 50%, #4D7C0F 100%)',
  },

  // ===========================================================================
  // PRODUCTIVITY (7 styles)
  // ===========================================================================

  {
    id: 'notion-clean',
    name: 'Notion Clean',
    category: 'productivity',
    description: 'Black and white with system fonts. Ultra-minimal where the UI disappears and content takes center stage. No shadows.',
    inspiration: 'Notion',
    tags: ['minimal', 'black-white', 'system-fonts', 'content-first', 'clean'],
    colors: {
      primary: '#2F3437',
      secondary: '#787774',
      accent: '#2EAADC',
      background: '#FFFFFF',
      surface: '#F7F6F3',
      text: '#37352F',
      textSecondary: '#787774',
      success: '#6BC950',
      warning: '#DFAB01',
      error: '#E03E3E',
    },
    typography: {
      headingFont: '-apple-system, BlinkMacSystemFont, sans-serif',
      bodyFont: '-apple-system, BlinkMacSystemFont, sans-serif',
      monoFont: 'SFMono-Regular, Menlo, monospace',
      scale: 'default',
    },
    borderRadius: 'subtle',
    shadowStyle: 'none',
    animationStyle: 'none',
    density: 'comfortable',
    mode: 'light',
    previewGradient: 'linear-gradient(135deg, #FFFFFF 0%, #F7F6F3 50%, #37352F 100%)',
  },

  {
    id: 'linear-precision',
    name: 'Linear Precision',
    category: 'productivity',
    description: 'Purple accent on dark backgrounds. Sharp corners, compact density, and developer-focused precision for issue tracking.',
    inspiration: 'Linear',
    tags: ['dark', 'purple', 'sharp', 'compact', 'developer'],
    colors: {
      primary: '#5E6AD2',
      secondary: '#8B5CF6',
      accent: '#A78BFA',
      background: '#0A0A0F',
      surface: '#16161F',
      text: '#F1F1F4',
      textSecondary: '#8A8F98',
      success: '#4ADE80',
      warning: '#FBBF24',
      error: '#F87171',
    },
    typography: {
      headingFont: 'Inter',
      bodyFont: 'Inter',
      monoFont: 'JetBrains Mono',
      scale: 'compact',
    },
    borderRadius: 'subtle',
    shadowStyle: 'none',
    animationStyle: 'subtle',
    density: 'compact',
    mode: 'dark',
    previewGradient: 'linear-gradient(135deg, #0A0A0F 0%, #16161F 50%, #5E6AD2 100%)',
  },

  {
    id: 'todoist-focus',
    name: 'Todoist Focus',
    category: 'productivity',
    description: 'Red accent on clean white. Task-oriented with subtle shadows and minimal distraction. Every pixel serves productivity.',
    inspiration: 'Todoist',
    tags: ['red', 'clean', 'task-oriented', 'focused', 'minimal'],
    colors: {
      primary: '#DB4035',
      secondary: '#FF9933',
      accent: '#DB4035',
      background: '#FFFFFF',
      surface: '#FAFAFA',
      text: '#202020',
      textSecondary: '#808080',
      success: '#058527',
      warning: '#FF9933',
      error: '#DB4035',
    },
    typography: {
      headingFont: 'Inter',
      bodyFont: 'Inter',
      monoFont: 'Fira Code',
      scale: 'default',
    },
    borderRadius: 'subtle',
    shadowStyle: 'subtle',
    animationStyle: 'subtle',
    density: 'comfortable',
    mode: 'light',
    previewGradient: 'linear-gradient(135deg, #FFFFFF 0%, #FAFAFA 50%, #DB4035 100%)',
  },

  {
    id: 'things-elegant',
    name: 'Things Elegant',
    category: 'productivity',
    description: 'Blue headers on white cards with refined typography. Apple-like polish with attention to every spacing detail.',
    inspiration: 'Things 3',
    tags: ['blue', 'elegant', 'apple-like', 'refined', 'polished'],
    colors: {
      primary: '#4A90D9',
      secondary: '#5BA4E5',
      accent: '#4A90D9',
      background: '#FFFFFF',
      surface: '#F5F7FA',
      text: '#1C1C1E',
      textSecondary: '#8E8E93',
      success: '#34C759',
      warning: '#FF9500',
      error: '#FF3B30',
    },
    typography: {
      headingFont: 'SF Pro Display, -apple-system, sans-serif',
      bodyFont: 'SF Pro Text, -apple-system, sans-serif',
      monoFont: 'SF Mono, SFMono-Regular, monospace',
      scale: 'default',
    },
    borderRadius: 'rounded',
    shadowStyle: 'subtle',
    animationStyle: 'smooth',
    density: 'comfortable',
    mode: 'light',
    previewGradient: 'linear-gradient(135deg, #FFFFFF 0%, #F5F7FA 50%, #4A90D9 100%)',
  },

  {
    id: 'obsidian-dark',
    name: 'Obsidian Dark',
    category: 'productivity',
    description: 'Pure dark mode with purple accents and monospace typography. Knowledge-graph aesthetic for power users and researchers.',
    inspiration: 'Obsidian',
    tags: ['dark', 'purple', 'monospace', 'knowledge', 'power-user'],
    colors: {
      primary: '#A855F7',
      secondary: '#7C3AED',
      accent: '#A855F7',
      background: '#1E1E1E',
      surface: '#262626',
      text: '#DCDDDE',
      textSecondary: '#999999',
      success: '#4ADE80',
      warning: '#FBBF24',
      error: '#F87171',
    },
    typography: {
      headingFont: 'Inter',
      bodyFont: 'JetBrains Mono',
      monoFont: 'JetBrains Mono',
      scale: 'default',
    },
    borderRadius: 'subtle',
    shadowStyle: 'none',
    animationStyle: 'none',
    density: 'comfortable',
    mode: 'dark',
    previewGradient: 'linear-gradient(135deg, #1E1E1E 0%, #262626 50%, #A855F7 100%)',
  },

  {
    id: 'craft-premium',
    name: 'Craft Premium',
    category: 'productivity',
    description: 'Warm grays with elegant serif headings. Spacious editorial feel with document-focused design and premium writing experience.',
    inspiration: 'Craft',
    tags: ['warm', 'serif', 'editorial', 'premium', 'writing'],
    colors: {
      primary: '#1A1A1A',
      secondary: '#4A4A4A',
      accent: '#0066FF',
      background: '#FFFDF8',
      surface: '#FFFFFF',
      text: '#1A1A1A',
      textSecondary: '#6B6B6B',
      success: '#34C759',
      warning: '#FF9500',
      error: '#FF3B30',
    },
    typography: {
      headingFont: 'New York, Georgia, serif',
      bodyFont: 'SF Pro Text, -apple-system, sans-serif',
      monoFont: 'SF Mono, monospace',
      scale: 'spacious',
    },
    borderRadius: 'rounded',
    shadowStyle: 'subtle',
    animationStyle: 'smooth',
    density: 'spacious',
    mode: 'light',
    previewGradient: 'linear-gradient(135deg, #FFFDF8 0%, #F5F3EE 50%, #0066FF 100%)',
  },

  {
    id: 'arc-browser',
    name: 'Arc Browser',
    category: 'productivity',
    description: 'Vibrant gradients with playful rounded elements. Bold colors that shift and change, creating a living, breathing interface.',
    inspiration: 'Arc Browser',
    tags: ['vibrant', 'gradient', 'playful', 'bold', 'colorful'],
    colors: {
      primary: '#6366F1',
      secondary: '#EC4899',
      accent: '#F59E0B',
      background: '#FAFAFA',
      surface: '#FFFFFF',
      text: '#1F2937',
      textSecondary: '#6B7280',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
    },
    typography: {
      headingFont: 'Inter',
      bodyFont: 'Inter',
      monoFont: 'JetBrains Mono',
      scale: 'default',
    },
    borderRadius: 'rounded',
    shadowStyle: 'elevated',
    animationStyle: 'playful',
    density: 'comfortable',
    mode: 'light',
    previewGradient: 'linear-gradient(135deg, #6366F1 0%, #EC4899 50%, #F59E0B 100%)',
  },

  // ===========================================================================
  // FINANCE (6 styles)
  // ===========================================================================

  {
    id: 'robinhood-bold',
    name: 'Robinhood Bold',
    category: 'finance',
    description: 'Bright green on black with bold numbers. Compact data-dense layouts designed for tracking gains and market movements.',
    inspiration: 'Robinhood',
    tags: ['green', 'dark', 'bold', 'compact', 'trading'],
    colors: {
      primary: '#00C805',
      secondary: '#5AC53B',
      accent: '#00C805',
      background: '#000000',
      surface: '#1E1E1E',
      text: '#FFFFFF',
      textSecondary: '#9E9E9E',
      success: '#00C805',
      warning: '#FF9800',
      error: '#FF5252',
    },
    typography: {
      headingFont: 'Inter',
      bodyFont: 'Inter',
      monoFont: 'JetBrains Mono',
      scale: 'compact',
    },
    borderRadius: 'subtle',
    shadowStyle: 'none',
    animationStyle: 'smooth',
    density: 'compact',
    mode: 'dark',
    previewGradient: 'linear-gradient(135deg, #000000 0%, #1E1E1E 50%, #00C805 100%)',
  },

  {
    id: 'revolut-modern',
    name: 'Revolut Modern',
    category: 'finance',
    description: 'Dark purple-blue with clean card layouts. Subtle gradients and modern European fintech aesthetic.',
    inspiration: 'Revolut',
    tags: ['dark', 'purple', 'modern', 'cards', 'fintech'],
    colors: {
      primary: '#0075EB',
      secondary: '#6C47FF',
      accent: '#00D4AA',
      background: '#0A0E17',
      surface: '#141B2D',
      text: '#FFFFFF',
      textSecondary: '#8B95A5',
      success: '#00D4AA',
      warning: '#FFB800',
      error: '#FF4444',
    },
    typography: {
      headingFont: 'Inter',
      bodyFont: 'Inter',
      monoFont: 'Space Mono',
      scale: 'default',
    },
    borderRadius: 'rounded',
    shadowStyle: 'subtle',
    animationStyle: 'smooth',
    density: 'comfortable',
    mode: 'dark',
    previewGradient: 'linear-gradient(135deg, #0A0E17 0%, #141B2D 50%, #6C47FF 100%)',
  },

  {
    id: 'wise-clean',
    name: 'Wise Clean',
    category: 'finance',
    description: 'Bright green on white with friendly rounded elements. Approachable and trustworthy design for money transfers.',
    inspiration: 'Wise (TransferWise)',
    tags: ['green', 'white', 'friendly', 'rounded', 'trustworthy'],
    colors: {
      primary: '#9FE870',
      secondary: '#37517E',
      accent: '#9FE870',
      background: '#FFFFFF',
      surface: '#F2F5F9',
      text: '#2E4057',
      textSecondary: '#6B7C93',
      success: '#9FE870',
      warning: '#FFB800',
      error: '#E53935',
    },
    typography: {
      headingFont: 'Inter',
      bodyFont: 'Inter',
      monoFont: 'Fira Code',
      scale: 'default',
    },
    borderRadius: 'rounded',
    shadowStyle: 'subtle',
    animationStyle: 'smooth',
    density: 'comfortable',
    mode: 'light',
    previewGradient: 'linear-gradient(135deg, #FFFFFF 0%, #F2F5F9 50%, #9FE870 100%)',
  },

  {
    id: 'mercury-minimal',
    name: 'Mercury Minimal',
    category: 'finance',
    description: 'Monochrome ultra-minimal design. Elegant simplicity with precise typography and restrained use of color.',
    inspiration: 'Mercury bank',
    tags: ['monochrome', 'minimal', 'elegant', 'precise', 'banking'],
    colors: {
      primary: '#1C1C1C',
      secondary: '#4A4A4A',
      accent: '#5046E5',
      background: '#FFFFFF',
      surface: '#F9F9F9',
      text: '#1C1C1C',
      textSecondary: '#6B6B6B',
      success: '#22C55E',
      warning: '#EAB308',
      error: '#EF4444',
    },
    typography: {
      headingFont: 'Inter',
      bodyFont: 'Inter',
      monoFont: 'Berkeley Mono, JetBrains Mono, monospace',
      scale: 'default',
    },
    borderRadius: 'subtle',
    shadowStyle: 'none',
    animationStyle: 'subtle',
    density: 'comfortable',
    mode: 'light',
    previewGradient: 'linear-gradient(135deg, #FFFFFF 0%, #F9F9F9 50%, #1C1C1C 100%)',
  },

  {
    id: 'coinbase-pro',
    name: 'Coinbase Pro',
    category: 'finance',
    description: 'Blue accent on dark mode with data-dense layouts. Professional trading interface with real-time chart aesthetics.',
    inspiration: 'Coinbase',
    tags: ['blue', 'dark', 'data-dense', 'trading', 'crypto'],
    colors: {
      primary: '#0052FF',
      secondary: '#1652F0',
      accent: '#0052FF',
      background: '#0A0B0D',
      surface: '#1E2025',
      text: '#FFFFFF',
      textSecondary: '#8A919E',
      success: '#05B169',
      warning: '#FFB800',
      error: '#CF202F',
    },
    typography: {
      headingFont: 'Inter',
      bodyFont: 'Inter',
      monoFont: 'JetBrains Mono',
      scale: 'compact',
    },
    borderRadius: 'subtle',
    shadowStyle: 'none',
    animationStyle: 'subtle',
    density: 'compact',
    mode: 'dark',
    previewGradient: 'linear-gradient(135deg, #0A0B0D 0%, #1E2025 50%, #0052FF 100%)',
  },

  {
    id: 'cash-app',
    name: 'Cash App',
    category: 'finance',
    description: 'Bold green with playful large typography. Simple, direct, and unapologetically bold in its visual approach.',
    inspiration: 'Cash App',
    tags: ['green', 'bold', 'playful', 'large-type', 'simple'],
    colors: {
      primary: '#00D632',
      secondary: '#006B1A',
      accent: '#00D632',
      background: '#FFFFFF',
      surface: '#F5F5F5',
      text: '#000000',
      textSecondary: '#666666',
      success: '#00D632',
      warning: '#FFB800',
      error: '#FF3B30',
    },
    typography: {
      headingFont: 'Inter',
      bodyFont: 'Inter',
      monoFont: 'Space Mono',
      scale: 'spacious',
    },
    borderRadius: 'rounded',
    shadowStyle: 'none',
    animationStyle: 'playful',
    density: 'spacious',
    mode: 'light',
    previewGradient: 'linear-gradient(135deg, #FFFFFF 0%, #F5F5F5 50%, #00D632 100%)',
  },

  // ===========================================================================
  // SOCIAL (5 styles)
  // ===========================================================================

  {
    id: 'instagram-warm',
    name: 'Instagram Warm',
    category: 'social',
    description: 'Warm gradients flowing from pink through orange to purple. White cards with rounded corners and visual-first layouts.',
    inspiration: 'Instagram',
    tags: ['gradient', 'warm', 'visual', 'rounded', 'stories'],
    colors: {
      primary: '#E1306C',
      secondary: '#F77737',
      accent: '#833AB4',
      background: '#FFFFFF',
      surface: '#FAFAFA',
      text: '#262626',
      textSecondary: '#8E8E8E',
      success: '#4CAF50',
      warning: '#FF9800',
      error: '#E53935',
    },
    typography: {
      headingFont: 'Inter',
      bodyFont: 'Inter',
      monoFont: 'Fira Code',
      scale: 'default',
    },
    borderRadius: 'rounded',
    shadowStyle: 'subtle',
    animationStyle: 'smooth',
    density: 'comfortable',
    mode: 'light',
    previewGradient: 'linear-gradient(135deg, #833AB4 0%, #E1306C 50%, #F77737 100%)',
  },

  {
    id: 'discord-gamer',
    name: 'Discord Gamer',
    category: 'social',
    description: 'Blurple on dark gray with rounded UI. Community-focused, compact, and playful with emoji-rich interactions.',
    inspiration: 'Discord',
    tags: ['blurple', 'dark', 'gaming', 'community', 'rounded'],
    colors: {
      primary: '#5865F2',
      secondary: '#57F287',
      accent: '#EB459E',
      background: '#313338',
      surface: '#2B2D31',
      text: '#F2F3F5',
      textSecondary: '#B5BAC1',
      success: '#57F287',
      warning: '#FEE75C',
      error: '#ED4245',
    },
    typography: {
      headingFont: 'Inter',
      bodyFont: 'Inter',
      monoFont: 'Consolas, monospace',
      scale: 'compact',
    },
    borderRadius: 'rounded',
    shadowStyle: 'none',
    animationStyle: 'playful',
    density: 'compact',
    mode: 'dark',
    previewGradient: 'linear-gradient(135deg, #313338 0%, #2B2D31 50%, #5865F2 100%)',
  },

  {
    id: 'threads-clean',
    name: 'Threads Clean',
    category: 'social',
    description: 'Black and white with system fonts. Text-first, conversation-focused design with minimal visual noise.',
    inspiration: 'Threads',
    tags: ['black-white', 'minimal', 'text-first', 'clean', 'conversation'],
    colors: {
      primary: '#000000',
      secondary: '#333333',
      accent: '#0095F6',
      background: '#FFFFFF',
      surface: '#F5F5F5',
      text: '#000000',
      textSecondary: '#737373',
      success: '#4CAF50',
      warning: '#FF9800',
      error: '#F44336',
    },
    typography: {
      headingFont: '-apple-system, BlinkMacSystemFont, sans-serif',
      bodyFont: '-apple-system, BlinkMacSystemFont, sans-serif',
      monoFont: 'SFMono-Regular, monospace',
      scale: 'default',
    },
    borderRadius: 'rounded',
    shadowStyle: 'none',
    animationStyle: 'subtle',
    density: 'comfortable',
    mode: 'light',
    previewGradient: 'linear-gradient(135deg, #FFFFFF 0%, #F5F5F5 50%, #000000 100%)',
  },

  {
    id: 'bereal-authentic',
    name: 'BeReal Authentic',
    category: 'social',
    description: 'Yellow accent with raw unpolished feel. Anti-perfection aesthetic that celebrates authenticity with bold contrasts.',
    inspiration: 'BeReal',
    tags: ['yellow', 'raw', 'authentic', 'bold', 'anti-polish'],
    colors: {
      primary: '#000000',
      secondary: '#333333',
      accent: '#FFFF00',
      background: '#FFFFFF',
      surface: '#F5F5F5',
      text: '#000000',
      textSecondary: '#666666',
      success: '#4CAF50',
      warning: '#FFFF00',
      error: '#FF3B30',
    },
    typography: {
      headingFont: 'Inter',
      bodyFont: 'Inter',
      monoFont: 'Menlo, monospace',
      scale: 'default',
    },
    borderRadius: 'rounded',
    shadowStyle: 'none',
    animationStyle: 'subtle',
    density: 'comfortable',
    mode: 'light',
    previewGradient: 'linear-gradient(135deg, #FFFFFF 0%, #FFFF00 50%, #000000 100%)',
  },

  {
    id: 'lemon8-fresh',
    name: 'Lemon8 Fresh',
    category: 'social',
    description: 'Pastel colors with soft gradients. Lifestyle aesthetic with gentle rounded elements and a fresh, youthful energy.',
    inspiration: 'Lemon8',
    tags: ['pastel', 'fresh', 'lifestyle', 'youthful', 'soft'],
    colors: {
      primary: '#FFE135',
      secondary: '#A8E6CF',
      accent: '#FFB7B2',
      background: '#FFFEF5',
      surface: '#FFFFFF',
      text: '#2D2D2D',
      textSecondary: '#7A7A7A',
      success: '#A8E6CF',
      warning: '#FFE135',
      error: '#FF6B6B',
    },
    typography: {
      headingFont: 'Poppins',
      bodyFont: 'Inter',
      monoFont: 'Fira Code',
      scale: 'default',
    },
    borderRadius: 'rounded',
    shadowStyle: 'subtle',
    animationStyle: 'playful',
    density: 'comfortable',
    mode: 'light',
    previewGradient: 'linear-gradient(135deg, #FFFEF5 0%, #A8E6CF 50%, #FFB7B2 100%)',
  },

  // ===========================================================================
  // ENTERTAINMENT (5 styles)
  // ===========================================================================

  {
    id: 'spotify-dark',
    name: 'Spotify Dark',
    category: 'entertainment',
    description: 'Green on black with bold typography. Card-based layouts with smooth transitions and album-art-forward design.',
    inspiration: 'Spotify',
    tags: ['green', 'dark', 'bold', 'cards', 'music'],
    colors: {
      primary: '#1DB954',
      secondary: '#191414',
      accent: '#1DB954',
      background: '#121212',
      surface: '#181818',
      text: '#FFFFFF',
      textSecondary: '#B3B3B3',
      success: '#1DB954',
      warning: '#FFA42B',
      error: '#F15E6C',
    },
    typography: {
      headingFont: 'Inter',
      bodyFont: 'Inter',
      monoFont: 'Fira Code',
      scale: 'default',
    },
    borderRadius: 'rounded',
    shadowStyle: 'none',
    animationStyle: 'smooth',
    density: 'comfortable',
    mode: 'dark',
    previewGradient: 'linear-gradient(135deg, #121212 0%, #181818 50%, #1DB954 100%)',
  },

  {
    id: 'netflix-cinematic',
    name: 'Netflix Cinematic',
    category: 'entertainment',
    description: 'Red on black with dramatic shadows. Cinematic feel with large imagery, bold contrasts, and immersive dark UI.',
    inspiration: 'Netflix',
    tags: ['red', 'dark', 'cinematic', 'dramatic', 'immersive'],
    colors: {
      primary: '#E50914',
      secondary: '#B81D24',
      accent: '#E50914',
      background: '#141414',
      surface: '#1F1F1F',
      text: '#FFFFFF',
      textSecondary: '#AAAAAA',
      success: '#46D369',
      warning: '#F5C518',
      error: '#E50914',
    },
    typography: {
      headingFont: 'Inter',
      bodyFont: 'Inter',
      monoFont: 'Fira Code',
      scale: 'default',
    },
    borderRadius: 'subtle',
    shadowStyle: 'dramatic',
    animationStyle: 'dramatic',
    density: 'comfortable',
    mode: 'dark',
    previewGradient: 'linear-gradient(135deg, #141414 0%, #1F1F1F 50%, #E50914 100%)',
  },

  {
    id: 'apple-music',
    name: 'Apple Music',
    category: 'entertainment',
    description: 'Pink and red gradients with blur effects. Premium feel with vibrancy, depth, and Apple-quality polish throughout.',
    inspiration: 'Apple Music',
    tags: ['pink', 'gradient', 'blur', 'premium', 'apple'],
    colors: {
      primary: '#FA2D48',
      secondary: '#FC3C44',
      accent: '#FA2D48',
      background: '#FFFFFF',
      surface: '#F5F5F7',
      text: '#1D1D1F',
      textSecondary: '#86868B',
      success: '#34C759',
      warning: '#FF9500',
      error: '#FF3B30',
    },
    typography: {
      headingFont: 'SF Pro Display, -apple-system, sans-serif',
      bodyFont: 'SF Pro Text, -apple-system, sans-serif',
      monoFont: 'SF Mono, monospace',
      scale: 'default',
    },
    borderRadius: 'rounded',
    shadowStyle: 'elevated',
    animationStyle: 'smooth',
    density: 'comfortable',
    mode: 'auto',
    previewGradient: 'linear-gradient(135deg, #FA2D48 0%, #FC3C44 50%, #FF6B8A 100%)',
  },

  {
    id: 'youtube-vibrant',
    name: 'YouTube Vibrant',
    category: 'entertainment',
    description: 'Red accent with white/dark adaptive design. Content-forward with thumbnail grids and creator-focused layouts.',
    inspiration: 'YouTube',
    tags: ['red', 'adaptive', 'content-forward', 'video', 'creator'],
    colors: {
      primary: '#FF0000',
      secondary: '#CC0000',
      accent: '#FF0000',
      background: '#FFFFFF',
      surface: '#F9F9F9',
      text: '#0F0F0F',
      textSecondary: '#606060',
      success: '#2BA640',
      warning: '#FF9800',
      error: '#FF0000',
    },
    typography: {
      headingFont: 'Roboto',
      bodyFont: 'Roboto',
      monoFont: 'Roboto Mono',
      scale: 'default',
    },
    borderRadius: 'rounded',
    shadowStyle: 'subtle',
    animationStyle: 'subtle',
    density: 'comfortable',
    mode: 'auto',
    previewGradient: 'linear-gradient(135deg, #FFFFFF 0%, #F9F9F9 50%, #FF0000 100%)',
  },

  {
    id: 'twitch-purple',
    name: 'Twitch Purple',
    category: 'entertainment',
    description: 'Purple on dark with gaming aesthetic. Bold accents, compact layouts, and high-energy design for live streaming.',
    inspiration: 'Twitch',
    tags: ['purple', 'dark', 'gaming', 'bold', 'streaming'],
    colors: {
      primary: '#9146FF',
      secondary: '#772CE8',
      accent: '#9146FF',
      background: '#0E0E10',
      surface: '#18181B',
      text: '#EFEFF1',
      textSecondary: '#ADADB8',
      success: '#00F593',
      warning: '#FFCA5F',
      error: '#EB0400',
    },
    typography: {
      headingFont: 'Inter',
      bodyFont: 'Inter',
      monoFont: 'JetBrains Mono',
      scale: 'compact',
    },
    borderRadius: 'subtle',
    shadowStyle: 'none',
    animationStyle: 'smooth',
    density: 'compact',
    mode: 'dark',
    previewGradient: 'linear-gradient(135deg, #0E0E10 0%, #18181B 50%, #9146FF 100%)',
  },

  // ===========================================================================
  // EDUCATION (5 styles)
  // ===========================================================================

  {
    id: 'duolingo-playful',
    name: 'Duolingo Playful',
    category: 'education',
    description: 'Green with bright colors and gamified elements. Rounded, playful animations, and reward-driven design that makes learning fun.',
    inspiration: 'Duolingo',
    tags: ['green', 'gamified', 'playful', 'rounded', 'rewards'],
    colors: {
      primary: '#58CC02',
      secondary: '#FF9600',
      accent: '#1CB0F6',
      background: '#FFFFFF',
      surface: '#F7F7F7',
      text: '#3C3C3C',
      textSecondary: '#777777',
      success: '#58CC02',
      warning: '#FF9600',
      error: '#FF4B4B',
    },
    typography: {
      headingFont: 'Nunito',
      bodyFont: 'Nunito',
      monoFont: 'Fira Code',
      scale: 'default',
    },
    borderRadius: 'rounded',
    shadowStyle: 'elevated',
    animationStyle: 'playful',
    density: 'comfortable',
    mode: 'light',
    previewGradient: 'linear-gradient(135deg, #FFFFFF 0%, #58CC02 50%, #FF9600 100%)',
  },

  {
    id: 'khan-academy',
    name: 'Khan Academy',
    category: 'education',
    description: 'Blue and green on clean white. Educational, accessible, and content-focused with clear hierarchy and navigation.',
    inspiration: 'Khan Academy',
    tags: ['blue', 'green', 'accessible', 'educational', 'clean'],
    colors: {
      primary: '#1865F2',
      secondary: '#14BF96',
      accent: '#1865F2',
      background: '#FFFFFF',
      surface: '#F6F7F8',
      text: '#21242C',
      textSecondary: '#6B6E74',
      success: '#14BF96',
      warning: '#FFB100',
      error: '#D92916',
    },
    typography: {
      headingFont: 'Lato',
      bodyFont: 'Lato',
      monoFont: 'Inconsolata',
      scale: 'default',
    },
    borderRadius: 'rounded',
    shadowStyle: 'subtle',
    animationStyle: 'subtle',
    density: 'comfortable',
    mode: 'light',
    previewGradient: 'linear-gradient(135deg, #FFFFFF 0%, #1865F2 50%, #14BF96 100%)',
  },

  {
    id: 'brilliant',
    name: 'Brilliant',
    category: 'education',
    description: 'Orange accent on dark mode with mathematical precision. Interactive puzzle-like design with colorful diagrams.',
    inspiration: 'Brilliant',
    tags: ['orange', 'dark', 'mathematical', 'interactive', 'puzzles'],
    colors: {
      primary: '#FF8C00',
      secondary: '#00A651',
      accent: '#FF8C00',
      background: '#1A1A2E',
      surface: '#252540',
      text: '#FFFFFF',
      textSecondary: '#A0A0B0',
      success: '#00A651',
      warning: '#FF8C00',
      error: '#FF4444',
    },
    typography: {
      headingFont: 'Inter',
      bodyFont: 'Inter',
      monoFont: 'JetBrains Mono',
      scale: 'default',
    },
    borderRadius: 'rounded',
    shadowStyle: 'subtle',
    animationStyle: 'smooth',
    density: 'comfortable',
    mode: 'dark',
    previewGradient: 'linear-gradient(135deg, #1A1A2E 0%, #252540 50%, #FF8C00 100%)',
  },

  {
    id: 'anki-scholar',
    name: 'Anki Scholar',
    category: 'education',
    description: 'Minimal blue with card-based layouts. Focused and distraction-free design optimized for spaced repetition learning.',
    inspiration: 'Anki',
    tags: ['blue', 'minimal', 'cards', 'focused', 'learning'],
    colors: {
      primary: '#2196F3',
      secondary: '#1976D2',
      accent: '#2196F3',
      background: '#FFFFFF',
      surface: '#F5F5F5',
      text: '#212121',
      textSecondary: '#757575',
      success: '#4CAF50',
      warning: '#FF9800',
      error: '#F44336',
    },
    typography: {
      headingFont: 'Inter',
      bodyFont: 'Inter',
      monoFont: 'Source Code Pro',
      scale: 'default',
    },
    borderRadius: 'subtle',
    shadowStyle: 'subtle',
    animationStyle: 'none',
    density: 'comfortable',
    mode: 'light',
    previewGradient: 'linear-gradient(135deg, #FFFFFF 0%, #F5F5F5 50%, #2196F3 100%)',
  },

  {
    id: 'coursera-academic',
    name: 'Coursera Academic',
    category: 'education',
    description: 'Blue on white with professional structured layouts. Clean, credential-focused design with clear learning paths.',
    inspiration: 'Coursera',
    tags: ['blue', 'professional', 'structured', 'academic', 'clean'],
    colors: {
      primary: '#0056D2',
      secondary: '#1F6FEB',
      accent: '#0056D2',
      background: '#FFFFFF',
      surface: '#F5F7FA',
      text: '#1F1F1F',
      textSecondary: '#5E5E5E',
      success: '#198754',
      warning: '#FFC107',
      error: '#DC3545',
    },
    typography: {
      headingFont: 'Source Sans Pro',
      bodyFont: 'Source Sans Pro',
      monoFont: 'Source Code Pro',
      scale: 'default',
    },
    borderRadius: 'subtle',
    shadowStyle: 'subtle',
    animationStyle: 'subtle',
    density: 'comfortable',
    mode: 'light',
    previewGradient: 'linear-gradient(135deg, #FFFFFF 0%, #F5F7FA 50%, #0056D2 100%)',
  },

  // ===========================================================================
  // HEALTH & FITNESS (5 styles)
  // ===========================================================================

  {
    id: 'apple-fitness',
    name: 'Apple Fitness',
    category: 'health',
    description: 'Neon activity rings on black. Bold gradients with energetic colors and data-rich fitness tracking aesthetics.',
    inspiration: 'Apple Fitness+',
    tags: ['neon', 'dark', 'rings', 'energetic', 'data-rich'],
    colors: {
      primary: '#FA114F',
      secondary: '#92E82A',
      accent: '#04E2F2',
      background: '#000000',
      surface: '#1C1C1E',
      text: '#FFFFFF',
      textSecondary: '#98989D',
      success: '#92E82A',
      warning: '#FFD60A',
      error: '#FA114F',
    },
    typography: {
      headingFont: 'SF Pro Display, -apple-system, sans-serif',
      bodyFont: 'SF Pro Text, -apple-system, sans-serif',
      monoFont: 'SF Mono, monospace',
      scale: 'default',
    },
    borderRadius: 'rounded',
    shadowStyle: 'none',
    animationStyle: 'smooth',
    density: 'comfortable',
    mode: 'dark',
    previewGradient: 'linear-gradient(135deg, #000000 0%, #FA114F 50%, #92E82A 100%)',
  },

  {
    id: 'strava-athletic',
    name: 'Strava Athletic',
    category: 'health',
    description: 'Orange on white with sporty data-rich layouts. Compact, achievement-focused design for athletes and runners.',
    inspiration: 'Strava',
    tags: ['orange', 'sporty', 'data-rich', 'compact', 'athletic'],
    colors: {
      primary: '#FC4C02',
      secondary: '#F26722',
      accent: '#FC4C02',
      background: '#FFFFFF',
      surface: '#F7F7F7',
      text: '#2D2D2D',
      textSecondary: '#6D6D78',
      success: '#28A745',
      warning: '#FFC107',
      error: '#DC3545',
    },
    typography: {
      headingFont: 'Inter',
      bodyFont: 'Inter',
      monoFont: 'JetBrains Mono',
      scale: 'compact',
    },
    borderRadius: 'subtle',
    shadowStyle: 'subtle',
    animationStyle: 'subtle',
    density: 'compact',
    mode: 'light',
    previewGradient: 'linear-gradient(135deg, #FFFFFF 0%, #F7F7F7 50%, #FC4C02 100%)',
  },

  {
    id: 'peloton-premium',
    name: 'Peloton Premium',
    category: 'health',
    description: 'Red on black with premium dark aesthetic. Motivational, high-energy design with leaderboard-driven competition.',
    inspiration: 'Peloton',
    tags: ['red', 'dark', 'premium', 'motivational', 'energy'],
    colors: {
      primary: '#D0021B',
      secondary: '#FF3347',
      accent: '#D0021B',
      background: '#1A1A1A',
      surface: '#2A2A2A',
      text: '#FFFFFF',
      textSecondary: '#AAAAAA',
      success: '#4CAF50',
      warning: '#FF9800',
      error: '#D0021B',
    },
    typography: {
      headingFont: 'Inter',
      bodyFont: 'Inter',
      monoFont: 'Fira Code',
      scale: 'default',
    },
    borderRadius: 'subtle',
    shadowStyle: 'subtle',
    animationStyle: 'smooth',
    density: 'comfortable',
    mode: 'dark',
    previewGradient: 'linear-gradient(135deg, #1A1A1A 0%, #2A2A2A 50%, #D0021B 100%)',
  },

  {
    id: 'myfitnesspal',
    name: 'MyFitnessPal',
    category: 'health',
    description: 'Blue and green with friendly data-forward design. Accessible calorie tracking with clear progress indicators.',
    inspiration: 'MyFitnessPal',
    tags: ['blue', 'green', 'friendly', 'data-forward', 'accessible'],
    colors: {
      primary: '#0070D1',
      secondary: '#00B050',
      accent: '#0070D1',
      background: '#FFFFFF',
      surface: '#F4F4F4',
      text: '#333333',
      textSecondary: '#666666',
      success: '#00B050',
      warning: '#FFB800',
      error: '#E53935',
    },
    typography: {
      headingFont: 'Inter',
      bodyFont: 'Inter',
      monoFont: 'Fira Code',
      scale: 'default',
    },
    borderRadius: 'rounded',
    shadowStyle: 'subtle',
    animationStyle: 'subtle',
    density: 'comfortable',
    mode: 'light',
    previewGradient: 'linear-gradient(135deg, #FFFFFF 0%, #0070D1 50%, #00B050 100%)',
  },

  {
    id: 'oura-ring',
    name: 'Oura Ring',
    category: 'health',
    description: 'Minimal silver and gray with premium health-data focus. Elegant restraint with precise data visualization.',
    inspiration: 'Oura Ring',
    tags: ['silver', 'minimal', 'premium', 'health-data', 'elegant'],
    colors: {
      primary: '#8B8B8B',
      secondary: '#C0C0C0',
      accent: '#6366F1',
      background: '#FFFFFF',
      surface: '#F8F8F8',
      text: '#1A1A1A',
      textSecondary: '#6B6B6B',
      success: '#34D399',
      warning: '#FBBF24',
      error: '#F87171',
    },
    typography: {
      headingFont: 'Inter',
      bodyFont: 'Inter',
      monoFont: 'JetBrains Mono',
      scale: 'default',
    },
    borderRadius: 'rounded',
    shadowStyle: 'subtle',
    animationStyle: 'smooth',
    density: 'comfortable',
    mode: 'light',
    previewGradient: 'linear-gradient(135deg, #FFFFFF 0%, #F8F8F8 50%, #8B8B8B 100%)',
  },

  // ===========================================================================
  // LIFESTYLE (5 styles)
  // ===========================================================================

  {
    id: 'airbnb-warm',
    name: 'Airbnb Warm',
    category: 'lifestyle',
    description: 'Coral/pink accent with warm photography. Rounded, friendly design that makes exploration feel inviting and personal.',
    inspiration: 'Airbnb',
    tags: ['coral', 'warm', 'photography', 'rounded', 'friendly'],
    colors: {
      primary: '#FF5A5F',
      secondary: '#00A699',
      accent: '#FF5A5F',
      background: '#FFFFFF',
      surface: '#F7F7F7',
      text: '#222222',
      textSecondary: '#717171',
      success: '#008A05',
      warning: '#FFB400',
      error: '#C13515',
    },
    typography: {
      headingFont: 'Cereal, Inter, sans-serif',
      bodyFont: 'Cereal, Inter, sans-serif',
      monoFont: 'Fira Code',
      scale: 'default',
    },
    borderRadius: 'rounded',
    shadowStyle: 'elevated',
    animationStyle: 'smooth',
    density: 'comfortable',
    mode: 'light',
    previewGradient: 'linear-gradient(135deg, #FFFFFF 0%, #FF5A5F 50%, #00A699 100%)',
  },

  {
    id: 'pinterest-visual',
    name: 'Pinterest Visual',
    category: 'lifestyle',
    description: 'Red accent with masonry grid layouts. Visual-first, clean design optimized for discovery and inspiration boards.',
    inspiration: 'Pinterest',
    tags: ['red', 'visual', 'masonry', 'discovery', 'inspiration'],
    colors: {
      primary: '#E60023',
      secondary: '#BD081C',
      accent: '#E60023',
      background: '#FFFFFF',
      surface: '#F5F5F5',
      text: '#333333',
      textSecondary: '#767676',
      success: '#3B8427',
      warning: '#EFB700',
      error: '#E60023',
    },
    typography: {
      headingFont: 'Inter',
      bodyFont: 'Inter',
      monoFont: 'Fira Code',
      scale: 'default',
    },
    borderRadius: 'rounded',
    shadowStyle: 'subtle',
    animationStyle: 'subtle',
    density: 'comfortable',
    mode: 'light',
    previewGradient: 'linear-gradient(135deg, #FFFFFF 0%, #F5F5F5 50%, #E60023 100%)',
  },

  {
    id: 'ikea-scandinavian',
    name: 'IKEA Scandinavian',
    category: 'lifestyle',
    description: 'Blue and yellow with clean functional design. Accessible, well-organized, and democratic Scandinavian aesthetic.',
    inspiration: 'IKEA',
    tags: ['blue', 'yellow', 'functional', 'accessible', 'scandinavian'],
    colors: {
      primary: '#0058A3',
      secondary: '#FFDB00',
      accent: '#FFDB00',
      background: '#FFFFFF',
      surface: '#F5F5F5',
      text: '#111111',
      textSecondary: '#484848',
      success: '#0A8A00',
      warning: '#FFDB00',
      error: '#E00751',
    },
    typography: {
      headingFont: 'Inter',
      bodyFont: 'Inter',
      monoFont: 'Source Code Pro',
      scale: 'default',
    },
    borderRadius: 'subtle',
    shadowStyle: 'subtle',
    animationStyle: 'subtle',
    density: 'comfortable',
    mode: 'light',
    previewGradient: 'linear-gradient(135deg, #FFFFFF 0%, #0058A3 50%, #FFDB00 100%)',
  },

  {
    id: 'muji-minimal',
    name: 'Muji Minimal',
    category: 'lifestyle',
    description: 'Beige and brown with ultra-minimal Japanese simplicity. No excess, no waste — only what is essential remains.',
    inspiration: 'Muji',
    tags: ['beige', 'brown', 'ultra-minimal', 'japanese', 'essential'],
    colors: {
      primary: '#8B6F47',
      secondary: '#A0845C',
      accent: '#C41E3A',
      background: '#FAF8F5',
      surface: '#FFFFFF',
      text: '#333333',
      textSecondary: '#7A7A7A',
      success: '#5B8C5A',
      warning: '#D4A843',
      error: '#C41E3A',
    },
    typography: {
      headingFont: 'Noto Sans',
      bodyFont: 'Noto Sans',
      monoFont: 'Noto Sans Mono',
      scale: 'default',
    },
    borderRadius: 'none',
    shadowStyle: 'none',
    animationStyle: 'none',
    density: 'spacious',
    mode: 'light',
    previewGradient: 'linear-gradient(135deg, #FAF8F5 0%, #E8E0D5 50%, #8B6F47 100%)',
  },

  {
    id: 'aesop-luxury',
    name: 'Aesop Luxury',
    category: 'lifestyle',
    description: 'Dark green and cream with serif typography. Luxury feel with editorial layouts and refined, understated elegance.',
    inspiration: 'Aesop',
    tags: ['green', 'cream', 'serif', 'luxury', 'editorial'],
    colors: {
      primary: '#2D4A3E',
      secondary: '#4A7C6B',
      accent: '#8B6914',
      background: '#F5F0E8',
      surface: '#FFFFFF',
      text: '#2D2D2D',
      textSecondary: '#6B6B6B',
      success: '#4A7C6B',
      warning: '#C4956A',
      error: '#9B2C2C',
    },
    typography: {
      headingFont: 'Cormorant Garamond',
      bodyFont: 'Karla',
      monoFont: 'JetBrains Mono',
      scale: 'spacious',
    },
    borderRadius: 'none',
    shadowStyle: 'none',
    animationStyle: 'subtle',
    density: 'spacious',
    mode: 'light',
    previewGradient: 'linear-gradient(135deg, #F5F0E8 0%, #2D4A3E 50%, #8B6914 100%)',
  },

  // ===========================================================================
  // BUSINESS (3 styles)
  // ===========================================================================

  {
    id: 'slack-professional',
    name: 'Slack Professional',
    category: 'business',
    description: 'Purple with multicolor channel accents. Friendly professional tone with rounded elements and collaborative energy.',
    inspiration: 'Slack',
    tags: ['purple', 'multicolor', 'professional', 'friendly', 'collaborative'],
    colors: {
      primary: '#4A154B',
      secondary: '#36C5F0',
      accent: '#ECB22E',
      background: '#FFFFFF',
      surface: '#F8F8F8',
      text: '#1D1C1D',
      textSecondary: '#616061',
      success: '#2EB67D',
      warning: '#ECB22E',
      error: '#E01E5A',
    },
    typography: {
      headingFont: 'Lato',
      bodyFont: 'Lato',
      monoFont: 'Fira Code',
      scale: 'default',
    },
    borderRadius: 'rounded',
    shadowStyle: 'subtle',
    animationStyle: 'subtle',
    density: 'comfortable',
    mode: 'light',
    previewGradient: 'linear-gradient(135deg, #4A154B 0%, #36C5F0 50%, #2EB67D 100%)',
  },

  {
    id: 'salesforce-enterprise',
    name: 'Salesforce Enterprise',
    category: 'business',
    description: 'Blue on white with enterprise-grade structure. Accessible, data-rich layouts designed for complex business workflows.',
    inspiration: 'Salesforce',
    tags: ['blue', 'enterprise', 'structured', 'accessible', 'data-rich'],
    colors: {
      primary: '#0176D3',
      secondary: '#032D60',
      accent: '#0176D3',
      background: '#FFFFFF',
      surface: '#F3F3F3',
      text: '#181818',
      textSecondary: '#444444',
      success: '#2E844A',
      warning: '#FE9339',
      error: '#EA001E',
    },
    typography: {
      headingFont: 'Salesforce Sans, Inter, sans-serif',
      bodyFont: 'Salesforce Sans, Inter, sans-serif',
      monoFont: 'Consolas, monospace',
      scale: 'default',
    },
    borderRadius: 'subtle',
    shadowStyle: 'subtle',
    animationStyle: 'subtle',
    density: 'compact',
    mode: 'light',
    previewGradient: 'linear-gradient(135deg, #FFFFFF 0%, #F3F3F3 50%, #0176D3 100%)',
  },

  {
    id: 'stripe-developer',
    name: 'Stripe Developer',
    category: 'business',
    description: 'Purple gradient with developer-friendly clean code aesthetic. Precise documentation style with excellent readability.',
    inspiration: 'Stripe',
    tags: ['purple', 'gradient', 'developer', 'clean', 'documentation'],
    colors: {
      primary: '#635BFF',
      secondary: '#0A2540',
      accent: '#635BFF',
      background: '#FFFFFF',
      surface: '#F6F9FC',
      text: '#0A2540',
      textSecondary: '#425466',
      success: '#30B130',
      warning: '#FFBB00',
      error: '#DF1B41',
    },
    typography: {
      headingFont: 'Inter',
      bodyFont: 'Inter',
      monoFont: 'JetBrains Mono',
      scale: 'default',
    },
    borderRadius: 'rounded',
    shadowStyle: 'elevated',
    animationStyle: 'smooth',
    density: 'comfortable',
    mode: 'light',
    previewGradient: 'linear-gradient(135deg, #635BFF 0%, #0A2540 50%, #635BFF 100%)',
  },

  // ===========================================================================
  // CREATIVE (3 styles)
  // ===========================================================================

  {
    id: 'figma-vibrant',
    name: 'Figma Vibrant',
    category: 'creative',
    description: 'Multi-color with creative bold energy. Playful design tool aesthetic with vibrant accents and collaborative spirit.',
    inspiration: 'Figma',
    tags: ['multicolor', 'creative', 'bold', 'playful', 'collaborative'],
    colors: {
      primary: '#0ACF83',
      secondary: '#A259FF',
      accent: '#F24E1E',
      background: '#FFFFFF',
      surface: '#F5F5F5',
      text: '#1E1E1E',
      textSecondary: '#6E6E6E',
      success: '#0ACF83',
      warning: '#FFCD29',
      error: '#F24E1E',
    },
    typography: {
      headingFont: 'Inter',
      bodyFont: 'Inter',
      monoFont: 'Fira Code',
      scale: 'default',
    },
    borderRadius: 'rounded',
    shadowStyle: 'subtle',
    animationStyle: 'playful',
    density: 'comfortable',
    mode: 'light',
    previewGradient: 'linear-gradient(135deg, #0ACF83 0%, #A259FF 50%, #F24E1E 100%)',
  },

  {
    id: 'procreate-artist',
    name: 'Procreate Artist',
    category: 'creative',
    description: 'Dark canvas with vibrant tool colors. Creative workspace aesthetic designed for artists and digital creators.',
    inspiration: 'Procreate',
    tags: ['dark', 'vibrant', 'canvas', 'artistic', 'creative'],
    colors: {
      primary: '#1A1A2E',
      secondary: '#16213E',
      accent: '#00D4FF',
      background: '#0F0F0F',
      surface: '#1A1A1A',
      text: '#FFFFFF',
      textSecondary: '#AAAAAA',
      success: '#00FF88',
      warning: '#FFD700',
      error: '#FF4757',
    },
    typography: {
      headingFont: 'Inter',
      bodyFont: 'Inter',
      monoFont: 'JetBrains Mono',
      scale: 'default',
    },
    borderRadius: 'rounded',
    shadowStyle: 'none',
    animationStyle: 'smooth',
    density: 'comfortable',
    mode: 'dark',
    previewGradient: 'linear-gradient(135deg, #0F0F0F 0%, #1A1A2E 50%, #00D4FF 100%)',
  },

  {
    id: 'vsco-film',
    name: 'VSCO Film',
    category: 'creative',
    description: 'Muted desaturated tones with film aesthetic. Minimal UI that stays out of the way, letting content speak for itself.',
    inspiration: 'VSCO',
    tags: ['muted', 'desaturated', 'film', 'minimal', 'content-first'],
    colors: {
      primary: '#2C2C2C',
      secondary: '#4A4A4A',
      accent: '#2C2C2C',
      background: '#FFFFFF',
      surface: '#F5F5F5',
      text: '#1A1A1A',
      textSecondary: '#8C8C8C',
      success: '#5B8C5A',
      warning: '#C4956A',
      error: '#9B4D4D',
    },
    typography: {
      headingFont: 'Inter',
      bodyFont: 'Inter',
      monoFont: 'Fira Code',
      scale: 'default',
    },
    borderRadius: 'subtle',
    shadowStyle: 'none',
    animationStyle: 'subtle',
    density: 'spacious',
    mode: 'light',
    previewGradient: 'linear-gradient(135deg, #F5F5F5 0%, #E0DDD5 50%, #2C2C2C 100%)',
  },
];

// ---------------------------------------------------------------------------
// Helper Functions
// ---------------------------------------------------------------------------

/** Get all styles for a given category */
export function getStylesByCategory(category: BrandingCategory): BrandingStyle[] {
  return BRANDING_STYLES.filter(s => s.category === category);
}

/** Find a style by its ID */
export function getStyleById(id: string): BrandingStyle | undefined {
  return BRANDING_STYLES.find(s => s.id === id);
}

/** Search styles by name, description, tags, or inspiration */
export function searchStyles(query: string): BrandingStyle[] {
  const q = query.toLowerCase();
  return BRANDING_STYLES.filter(s =>
    s.name.toLowerCase().includes(q) ||
    s.description.toLowerCase().includes(q) ||
    s.inspiration.toLowerCase().includes(q) ||
    s.tags.some(t => t.includes(q))
  );
}

/** Get all unique tags across all styles */
export function getAllTags(): string[] {
  const tags = new Set<string>();
  BRANDING_STYLES.forEach(s => s.tags.forEach(t => tags.add(t)));
  return Array.from(tags).sort();
}
