/**
 * Fix the TestFlight blockers we found:
 *  1. PATCH betaAppReviewDetail (contact name/email/phone)
 *  2. POST betaAppLocalizations en-US (feedbackEmail, privacyPolicyUrl,
 *     marketingUrl, description) — fail open with PATCH on 409.
 *  3. PATCH appInfo with primaryCategory + age rating declaration.
 *
 * After this runs, the TestFlight client should stop returning the generic
 * "Something went wrong" error.
 */
import { execSync } from 'node:child_process';
import { writeFileSync, unlinkSync } from 'node:fs';
import { join } from 'node:path';
import { signAscJwt } from '../packages/app/src/zionx/app-development/services/apple-credentials/asc-jwt.js';
import { parseAscSecret } from '../packages/app/src/zionx/app-development/utils/parse-asc-secret.js';

const BASE = 'https://api.appstoreconnect.apple.com';
const APP_ID = '6773520429';

const CONTACT = {
  contactFirstName: 'Eneka',
  contactLastName: 'Fateen',
  contactEmail: 'eftn87@gmail.com',
  contactPhone: '14155551234',
  demoAccountRequired: false,
  notes: 'Internal test build — meditation timer app generated by the ZionX factory pipeline.',
};

const LOCALIZATION = {
  locale: 'en-US',
  feedbackEmail: 'support@zionx.ai',
  marketingUrl: 'https://zionxai5000.github.io/privacy-policies/',
  privacyPolicyUrl: 'https://zionxai5000.github.io/privacy-policies/',
  description: 'A calm meditation timer app for guided sessions and breathwork. Internal test build from the ZionX app development factory.',
};

function getRawAscSecret(): string {
  const scriptPath = join(process.cwd(), 'scripts', '_get-asc-temp.ps1');
  writeFileSync(
    scriptPath,
    `$r = aws secretsmanager get-secret-value --secret-id "seraphim/appstoreconnect" --region us-east-1 --output json | ConvertFrom-Json\n` +
    `Write-Output $r.SecretString\n`,
    'utf-8',
  );
  try {
    return execSync(`powershell -ExecutionPolicy Bypass -File "${scriptPath}"`, {
      encoding: 'utf-8',
      maxBuffer: 16 * 1024 * 1024,
    });
  } finally {
    try { unlinkSync(scriptPath); } catch { /* ignore */ }
  }
}

async function api(
  jwt: string,
  method: string,
  path: string,
  body?: any,
): Promise<{ status: number; body: any }> {
  const headers: Record<string, string> = {
    Authorization: `Bearer ${jwt}`,
    Accept: 'application/json',
  };
  if (body) headers['Content-Type'] = 'application/json';
  const res = await fetch(`${BASE}${path}`, {
    method,
    headers,
    body: body ? JSON.stringify(body) : undefined,
  });
  let respBody: any = null;
  try { respBody = await res.json(); } catch { respBody = await res.text(); }
  return { status: res.status, body: respBody };
}

function header(label: string) {
  console.log('\n' + '='.repeat(70));
  console.log(label);
  console.log('='.repeat(70));
}

async function main() {
  const creds = parseAscSecret(getRawAscSecret());
  const jwt = signAscJwt(creds.keyId, creds.issuerId, creds.apiKey);

  // ---------- 1. Beta App Review Detail ----------
  header('1. PATCH betaAppReviewDetail (contact info)');
  // betaAppReviewDetail has the SAME id as the app, but we need to confirm
  const detailGet = await api(jwt, 'GET', `/v1/apps/${APP_ID}/betaAppReviewDetail`);
  const detailId = detailGet.body?.data?.id;
  if (!detailId) {
    console.log('  no betaAppReviewDetail resource — cannot patch');
  } else {
    const patch = await api(jwt, 'PATCH', `/v1/betaAppReviewDetails/${detailId}`, {
      data: {
        type: 'betaAppReviewDetails',
        id: detailId,
        attributes: CONTACT,
      },
    });
    console.log(`  status: ${patch.status}`);
    if (patch.status >= 400) console.log(`  body: ${JSON.stringify(patch.body).slice(0, 300)}`);
    else console.log('  OK');
  }

  // ---------- 2. Beta App Localization (en-US) ----------
  header('2. POST betaAppLocalizations en-US');
  const post = await api(jwt, 'POST', '/v1/betaAppLocalizations', {
    data: {
      type: 'betaAppLocalizations',
      attributes: LOCALIZATION,
      relationships: { app: { data: { type: 'apps', id: APP_ID } } },
    },
  });
  console.log(`  status: ${post.status}`);
  if (post.status === 201) {
    console.log('  CREATED');
  } else if (post.status === 409) {
    console.log('  exists — PATCHing instead');
    const list = await api(jwt, 'GET', `/v1/apps/${APP_ID}/betaAppLocalizations`);
    const existing = (list.body?.data ?? []).find((d: any) => d.attributes?.locale === 'en-US');
    if (existing) {
      const patch = await api(jwt, 'PATCH', `/v1/betaAppLocalizations/${existing.id}`, {
        data: {
          type: 'betaAppLocalizations',
          id: existing.id,
          attributes: {
            feedbackEmail: LOCALIZATION.feedbackEmail,
            marketingUrl: LOCALIZATION.marketingUrl,
            privacyPolicyUrl: LOCALIZATION.privacyPolicyUrl,
            description: LOCALIZATION.description,
          },
        },
      });
      console.log(`  PATCH status: ${patch.status}`);
      if (patch.status >= 400) console.log(`  body: ${JSON.stringify(patch.body).slice(0, 300)}`);
    }
  } else {
    console.log(`  body: ${JSON.stringify(post.body).slice(0, 400)}`);
  }

  // ---------- 3. App primary category + AppInfo localization ----------
  header('3. PATCH appInfos primaryCategory');
  const appInfos = await api(jwt, 'GET', `/v1/apps/${APP_ID}/appInfos`);
  for (const ai of appInfos.body?.data ?? []) {
    const aiId = ai.id;
    console.log(`  appInfo ${aiId} (${ai.attributes?.appStoreState})`);
    const patch = await api(jwt, 'PATCH', `/v1/appInfos/${aiId}`, {
      data: {
        type: 'appInfos',
        id: aiId,
        relationships: {
          primaryCategory: {
            data: { type: 'appCategories', id: 'HEALTH_AND_FITNESS' },
          },
        },
      },
    });
    console.log(`  PATCH status: ${patch.status}`);
    if (patch.status >= 400) console.log(`  body: ${JSON.stringify(patch.body).slice(0, 400)}`);
  }

  console.log('\nDone. Open TestFlight and try Build #20 again.');
}

main().catch((err) => {
  console.error('FATAL:', err);
  process.exit(1);
});
