/**
 * ZionX App Studio — Autonomous Ideation Pipeline View
 *
 * Displays a ranked pipeline of app ideas generated by the autonomous
 * ideation engine. Each idea card shows: app name, predicted downloads,
 * predicted revenue, competition level, niche score, and status.
 *
 * Supports filtering by category, revenue potential, competition level,
 * and technical feasibility. Clicking an idea shows full market analysis.
 * Dismiss and bookmark actions per idea. WebSocket for real-time updates.
 *
 * Requirements: 45e.16, 45e.17, 45e.18, 45e.19
 */

// ---------------------------------------------------------------------------
// Types (mirrors pipeline-manager.ts AppIdea)
// ---------------------------------------------------------------------------

export type IdeaSource = 'autonomous' | 'manual';
export type IdeaStatus = 'pipeline' | 'generating' | 'generated' | 'published' | 'dismissed' | 'bookmarked';
export type CompetitionLevel = 'low' | 'medium' | 'high';

export interface AppIdea {
  id: string;
  name: string;
  valueProposition: string;
  targetAudience: string;
  monetizationModel: string;
  category: string;
  predictedDownloads: number;
  predictedRevenue: number;
  competitionLevel: CompetitionLevel;
  nicheScore: number;
  technicalFeasibility: number;
  source: IdeaSource;
  status: IdeaStatus;
  createdAt: string;
  lastActionAt: string;
  metadata: Record<string, unknown>;
}

export interface PipelineFilter {
  category?: string;
  minRevenue?: number;
  maxCompetition?: CompetitionLevel;
  minFeasibility?: number;
}

// ---------------------------------------------------------------------------
// Sample Pipeline Data
// ---------------------------------------------------------------------------

const SAMPLE_IDEAS: AppIdea[] = [
  {
    id: '1',
    name: 'ZenFocus — Pomodoro + Ambient Sounds',
    valueProposition: 'Combines pomodoro timer with curated ambient soundscapes for deep work sessions',
    targetAudience: 'Remote workers and students aged 18-35',
    monetizationModel: 'Freemium with $4.99/mo premium sounds',
    category: 'Productivity',
    predictedDownloads: 85000,
    predictedRevenue: 12500,
    competitionLevel: 'medium',
    nicheScore: 78,
    technicalFeasibility: 92,
    source: 'autonomous',
    status: 'pipeline',
    createdAt: new Date().toISOString(),
    lastActionAt: new Date().toISOString(),
    metadata: { researchCycleId: 'rc-001' },
  },
  {
    id: '2',
    name: 'PetPal — AI Pet Health Tracker',
    valueProposition: 'AI-powered pet health monitoring with symptom checker and vet appointment scheduling',
    targetAudience: 'Pet owners aged 25-45 in urban areas',
    monetizationModel: 'Subscription $6.99/mo with vet consultation add-on',
    category: 'Health & Fitness',
    predictedDownloads: 120000,
    predictedRevenue: 28000,
    competitionLevel: 'low',
    nicheScore: 91,
    technicalFeasibility: 85,
    source: 'autonomous',
    status: 'pipeline',
    createdAt: new Date().toISOString(),
    lastActionAt: new Date().toISOString(),
    metadata: { researchCycleId: 'rc-001' },
  },
  {
    id: '3',
    name: 'BudgetBuddy — Envelope Budgeting',
    valueProposition: 'Digital envelope budgeting with bank sync and spending insights',
    targetAudience: 'Young professionals managing first salary',
    monetizationModel: 'Freemium with $3.99/mo bank sync',
    category: 'Finance',
    predictedDownloads: 65000,
    predictedRevenue: 8500,
    competitionLevel: 'high',
    nicheScore: 62,
    technicalFeasibility: 78,
    source: 'autonomous',
    status: 'pipeline',
    createdAt: new Date().toISOString(),
    lastActionAt: new Date().toISOString(),
    metadata: { researchCycleId: 'rc-002' },
  },
  {
    id: '4',
    name: 'MealPrep AI — Weekly Meal Planner',
    valueProposition: 'AI generates personalized weekly meal plans with grocery lists and nutritional tracking',
    targetAudience: 'Health-conscious adults and families',
    monetizationModel: 'Subscription $5.99/mo with family plan at $9.99/mo',
    category: 'Food & Drink',
    predictedDownloads: 95000,
    predictedRevenue: 18000,
    competitionLevel: 'medium',
    nicheScore: 82,
    technicalFeasibility: 88,
    source: 'autonomous',
    status: 'generating',
    createdAt: new Date().toISOString(),
    lastActionAt: new Date().toISOString(),
    metadata: { researchCycleId: 'rc-002' },
  },
  {
    id: '5',
    name: 'SkillStack — Micro-Learning Habits',
    valueProposition: '5-minute daily skill-building lessons with streak tracking and spaced repetition',
    targetAudience: 'Lifelong learners and career changers',
    monetizationModel: 'Freemium with $7.99/mo all-access',
    category: 'Education',
    predictedDownloads: 150000,
    predictedRevenue: 35000,
    competitionLevel: 'low',
    nicheScore: 88,
    technicalFeasibility: 90,
    source: 'autonomous',
    status: 'pipeline',
    createdAt: new Date().toISOString(),
    lastActionAt: new Date().toISOString(),
    metadata: { researchCycleId: 'rc-003' },
  },
];

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const CATEGORIES = ['All', 'Productivity', 'Health & Fitness', 'Finance', 'Food & Drink', 'Education', 'Lifestyle', 'Entertainment'];

const COMPETITION_ORDER: Record<CompetitionLevel, number> = { low: 1, medium: 2, high: 3 };

// ---------------------------------------------------------------------------
// IdeationPipelineView
// ---------------------------------------------------------------------------

export interface IdeationPipelineViewOptions {
  onGenerate?: (ideaId: string) => void;
  onDismiss?: (ideaId: string) => void;
  onBookmark?: (ideaId: string) => void;
}

export class IdeationPipelineView {
  private container: HTMLElement;
  private ideas: AppIdea[] = [...SAMPLE_IDEAS];
  private filter: PipelineFilter = {};
  private activeCategory: string = 'All';
  private selectedIdeaId: string | null = null;
  private options: IdeationPipelineViewOptions;
  private ws: WebSocket | null = null;

  constructor(container: HTMLElement, options: IdeationPipelineViewOptions = {}) {
    this.container = container;
    this.options = options;
  }

  mount(): void {
    this.render();
    this.attachListeners();
    this.connectWebSocket();
  }

  unmount(): void {
    this.container.innerHTML = '';
    this.disconnectWebSocket();
  }

  /** Update pipeline ideas from external source (e.g., WebSocket push) */
  updateIdeas(ideas: AppIdea[]): void {
    this.ideas = ideas;
    this.render();
    this.attachListeners();
  }

  // ---------------------------------------------------------------------------
  // WebSocket Connection
  // ---------------------------------------------------------------------------

  private connectWebSocket(): void {
    try {
      const apiUrl = (window as any).__SERAPHIM_API_URL__ || (window.location.origin + '/api');
      const wsBase = apiUrl.replace(/\/api$/, '').replace(/^http/, 'ws');
      const wsUrl = `${wsBase}/ws`;
      this.ws = new WebSocket(wsUrl);

      this.ws.onmessage = (event: MessageEvent) => {
        try {
          const message = JSON.parse(event.data as string);
          if (message.type === 'app.pipeline.updated' || message.type === 'app.idea.ranked') {
            if (message.data?.ideas) {
              this.updateIdeas(message.data.ideas as AppIdea[]);
            }
          }
        } catch {
          // Ignore malformed messages
        }
      };

      this.ws.onerror = () => {
        // Silent — pipeline still works with sample data
      };
    } catch {
      // WebSocket not available — continue with sample data
    }
  }

  private disconnectWebSocket(): void {
    if (this.ws) {
      this.ws.onmessage = null;
      this.ws.onerror = null;
      this.ws.close();
      this.ws = null;
    }
  }

  // ---------------------------------------------------------------------------
  // Filtering
  // ---------------------------------------------------------------------------

  private getFilteredIdeas(): AppIdea[] {
    let filtered = this.ideas.filter(
      (idea) => idea.status !== 'dismissed',
    );

    if (this.activeCategory !== 'All') {
      filtered = filtered.filter((i) => i.category === this.activeCategory);
    }
    if (this.filter.minRevenue !== undefined) {
      filtered = filtered.filter((i) => i.predictedRevenue >= this.filter.minRevenue!);
    }
    if (this.filter.maxCompetition) {
      const maxOrder = COMPETITION_ORDER[this.filter.maxCompetition];
      filtered = filtered.filter((i) => COMPETITION_ORDER[i.competitionLevel] <= maxOrder);
    }
    if (this.filter.minFeasibility !== undefined) {
      filtered = filtered.filter((i) => i.technicalFeasibility >= this.filter.minFeasibility!);
    }

    // Sort by composite score (same as pipeline-manager)
    return filtered.sort((a, b) => this.computeScore(b) - this.computeScore(a));
  }

  private computeScore(idea: AppIdea): number {
    const downloadScore = Math.min(idea.predictedDownloads / 100000, 1) * 40;
    const revenueScore = Math.min(idea.predictedRevenue / 10000, 1) * 40;
    const competitionScore = (1 - (COMPETITION_ORDER[idea.competitionLevel] - 1) / 2) * 20;
    return downloadScore + revenueScore + competitionScore;
  }

  // ---------------------------------------------------------------------------
  // Rendering
  // ---------------------------------------------------------------------------

  private render(): void {
    const selectedIdea = this.selectedIdeaId
      ? this.ideas.find((i) => i.id === this.selectedIdeaId) ?? null
      : null;

    if (selectedIdea) {
      this.container.innerHTML = this.renderDetailView(selectedIdea);
    } else {
      this.container.innerHTML = this.renderPipelineList();
    }
  }

  private renderPipelineList(): string {
    const filteredIdeas = this.getFilteredIdeas();

    return `
      <div class="pipeline-view">
        <div class="pipeline-view__header">
          <h3 class="pipeline-view__title">🚀 App Ideation Pipeline</h3>
          <span class="pipeline-view__count">${filteredIdeas.length} ideas</span>
        </div>

        ${this.renderFilters()}

        <div class="pipeline-view__list" id="pipeline-idea-list">
          ${filteredIdeas.length > 0
            ? filteredIdeas.map((idea) => this.renderIdeaCard(idea)).join('')
            : '<div class="pipeline-view__empty">No ideas match current filters. Adjust filters or wait for new research cycles.</div>'
          }
        </div>
      </div>
    `;
  }

  private renderFilters(): string {
    const categoryTabs = CATEGORIES.map(
      (cat) =>
        `<button class="pipeline-view__filter-tab ${cat === this.activeCategory ? 'pipeline-view__filter-tab--active' : ''}" data-filter-category="${cat}">${cat}</button>`,
    ).join('');

    return `
      <div class="pipeline-view__filters">
        <div class="pipeline-view__filter-row">
          ${categoryTabs}
        </div>
        <div class="pipeline-view__filter-row pipeline-view__filter-row--secondary">
          <select class="pipeline-view__filter-select" id="filter-revenue" aria-label="Revenue potential filter">
            <option value="">Revenue: Any</option>
            <option value="5000" ${this.filter.minRevenue === 5000 ? 'selected' : ''}>$5K+/mo</option>
            <option value="10000" ${this.filter.minRevenue === 10000 ? 'selected' : ''}>$10K+/mo</option>
            <option value="25000" ${this.filter.minRevenue === 25000 ? 'selected' : ''}>$25K+/mo</option>
          </select>
          <select class="pipeline-view__filter-select" id="filter-competition" aria-label="Competition level filter">
            <option value="">Competition: Any</option>
            <option value="low" ${this.filter.maxCompetition === 'low' ? 'selected' : ''}>Low only</option>
            <option value="medium" ${this.filter.maxCompetition === 'medium' ? 'selected' : ''}>Low–Medium</option>
            <option value="high" ${this.filter.maxCompetition === 'high' ? 'selected' : ''}>All levels</option>
          </select>
          <select class="pipeline-view__filter-select" id="filter-feasibility" aria-label="Technical feasibility filter">
            <option value="">Feasibility: Any</option>
            <option value="90" ${this.filter.minFeasibility === 90 ? 'selected' : ''}>90%+</option>
            <option value="80" ${this.filter.minFeasibility === 80 ? 'selected' : ''}>80%+</option>
            <option value="70" ${this.filter.minFeasibility === 70 ? 'selected' : ''}>70%+</option>
          </select>
        </div>
      </div>
    `;
  }

  private renderIdeaCard(idea: AppIdea): string {
    const competitionClass = `pipeline-view__competition--${idea.competitionLevel}`;
    const statusClass = `pipeline-view__status--${idea.status}`;
    const statusLabel = this.getStatusLabel(idea.status);

    return `
      <div class="pipeline-view__card" data-idea-id="${idea.id}" role="button" tabindex="0" aria-label="View details for ${idea.name}">
        <div class="pipeline-view__card-header">
          <span class="pipeline-view__card-name">${idea.name}</span>
          <span class="pipeline-view__card-status ${statusClass}">${statusLabel}</span>
        </div>
        <div class="pipeline-view__card-metrics">
          <span class="pipeline-view__metric" title="Predicted monthly downloads">
            📥 ${this.formatNumber(idea.predictedDownloads)}
          </span>
          <span class="pipeline-view__metric" title="Predicted monthly revenue">
            💰 $${this.formatNumber(idea.predictedRevenue)}/mo
          </span>
          <span class="pipeline-view__metric ${competitionClass}" title="Competition level">
            ⚔️ ${idea.competitionLevel}
          </span>
          <span class="pipeline-view__metric" title="Niche score (0-100)">
            🎯 ${idea.nicheScore}
          </span>
        </div>
        <div class="pipeline-view__card-actions">
          ${idea.status === 'pipeline' || idea.status === 'bookmarked'
            ? `<button class="pipeline-view__btn pipeline-view__btn--generate" data-generate-id="${idea.id}" title="Generate this app">Generate →</button>`
            : ''
          }
          ${idea.status === 'pipeline'
            ? `<button class="pipeline-view__btn pipeline-view__btn--bookmark" data-bookmark-id="${idea.id}" title="Bookmark for later">🔖</button>`
            : ''
          }
          ${idea.status !== 'dismissed'
            ? `<button class="pipeline-view__btn pipeline-view__btn--dismiss" data-dismiss-id="${idea.id}" title="Dismiss idea">✕</button>`
            : ''
          }
        </div>
      </div>
    `;
  }

  private renderDetailView(idea: AppIdea): string {
    const competitionClass = `pipeline-view__competition--${idea.competitionLevel}`;

    return `
      <div class="pipeline-view pipeline-view--detail">
        <div class="pipeline-view__detail-header">
          <button class="pipeline-view__back-btn" id="pipeline-back" aria-label="Back to pipeline list">← Back to Pipeline</button>
          <div class="pipeline-view__detail-actions">
            ${idea.status === 'pipeline' || idea.status === 'bookmarked'
              ? `<button class="pipeline-view__btn pipeline-view__btn--generate pipeline-view__btn--lg" data-generate-id="${idea.id}">Generate This App →</button>`
              : ''
            }
            <button class="pipeline-view__btn pipeline-view__btn--bookmark" data-bookmark-id="${idea.id}">🔖 Bookmark</button>
            <button class="pipeline-view__btn pipeline-view__btn--dismiss" data-dismiss-id="${idea.id}">✕ Dismiss</button>
          </div>
        </div>

        <div class="pipeline-view__detail-content">
          <h3 class="pipeline-view__detail-title">${idea.name}</h3>
          <p class="pipeline-view__detail-value-prop">${idea.valueProposition}</p>

          <div class="pipeline-view__detail-section">
            <h4>Market Analysis</h4>
            <div class="pipeline-view__detail-grid">
              <div class="pipeline-view__detail-stat">
                <span class="pipeline-view__detail-stat-label">Predicted Downloads</span>
                <span class="pipeline-view__detail-stat-value">📥 ${this.formatNumber(idea.predictedDownloads)}/mo</span>
              </div>
              <div class="pipeline-view__detail-stat">
                <span class="pipeline-view__detail-stat-label">Predicted Revenue</span>
                <span class="pipeline-view__detail-stat-value">💰 $${this.formatNumber(idea.predictedRevenue)}/mo</span>
              </div>
              <div class="pipeline-view__detail-stat">
                <span class="pipeline-view__detail-stat-label">Competition Level</span>
                <span class="pipeline-view__detail-stat-value ${competitionClass}">⚔️ ${idea.competitionLevel.charAt(0).toUpperCase() + idea.competitionLevel.slice(1)}</span>
              </div>
              <div class="pipeline-view__detail-stat">
                <span class="pipeline-view__detail-stat-label">Niche Score</span>
                <span class="pipeline-view__detail-stat-value">🎯 ${idea.nicheScore}/100</span>
              </div>
            </div>
          </div>

          <div class="pipeline-view__detail-section">
            <h4>Competitor Breakdown</h4>
            <div class="pipeline-view__detail-competitors">
              <p class="pipeline-view__detail-text">Category: <strong>${idea.category}</strong></p>
              <p class="pipeline-view__detail-text">Target Audience: ${idea.targetAudience}</p>
              <p class="pipeline-view__detail-text">Competition in this niche is <strong>${idea.competitionLevel}</strong> — ${this.getCompetitionDescription(idea.competitionLevel)}</p>
            </div>
          </div>

          <div class="pipeline-view__detail-section">
            <h4>Revenue Model</h4>
            <div class="pipeline-view__detail-revenue">
              <p class="pipeline-view__detail-text">Monetization: <strong>${idea.monetizationModel}</strong></p>
              <p class="pipeline-view__detail-text">Projected annual revenue: <strong>$${this.formatNumber(idea.predictedRevenue * 12)}</strong></p>
            </div>
          </div>

          <div class="pipeline-view__detail-section">
            <h4>Niche Scoring Factors</h4>
            <div class="pipeline-view__detail-scoring">
              <div class="pipeline-view__score-bar">
                <span class="pipeline-view__score-label">Niche Score</span>
                <div class="pipeline-view__score-track">
                  <div class="pipeline-view__score-fill" style="width: ${idea.nicheScore}%"></div>
                </div>
                <span class="pipeline-view__score-value">${idea.nicheScore}/100</span>
              </div>
              <div class="pipeline-view__score-bar">
                <span class="pipeline-view__score-label">Technical Feasibility</span>
                <div class="pipeline-view__score-track">
                  <div class="pipeline-view__score-fill" style="width: ${idea.technicalFeasibility}%"></div>
                </div>
                <span class="pipeline-view__score-value">${idea.technicalFeasibility}/100</span>
              </div>
              <div class="pipeline-view__score-bar">
                <span class="pipeline-view__score-label">Market Demand</span>
                <div class="pipeline-view__score-track">
                  <div class="pipeline-view__score-fill" style="width: ${Math.min(idea.predictedDownloads / 1500, 100)}%"></div>
                </div>
                <span class="pipeline-view__score-value">${Math.round(Math.min(idea.predictedDownloads / 1500, 100))}/100</span>
              </div>
              <div class="pipeline-view__score-bar">
                <span class="pipeline-view__score-label">Revenue Potential</span>
                <div class="pipeline-view__score-track">
                  <div class="pipeline-view__score-fill" style="width: ${Math.min(idea.predictedRevenue / 350, 100)}%"></div>
                </div>
                <span class="pipeline-view__score-value">${Math.round(Math.min(idea.predictedRevenue / 350, 100))}/100</span>
              </div>
            </div>
          </div>

          <div class="pipeline-view__detail-section">
            <h4>Metadata</h4>
            <p class="pipeline-view__detail-text pipeline-view__detail-text--muted">
              Source: ${idea.source === 'autonomous' ? '🤖 Autonomous Research' : '👑 King Input'} · 
              Created: ${new Date(idea.createdAt).toLocaleDateString()} · 
              Status: ${this.getStatusLabel(idea.status)}
            </p>
          </div>
        </div>
      </div>
    `;
  }

  // ---------------------------------------------------------------------------
  // Event Listeners
  // ---------------------------------------------------------------------------

  private attachListeners(): void {
    // Category filter tabs
    this.container.querySelectorAll('[data-filter-category]').forEach((tab) => {
      tab.addEventListener('click', () => {
        this.activeCategory = (tab as HTMLElement).dataset.filterCategory!;
        this.render();
        this.attachListeners();
      });
    });

    // Revenue filter
    const revenueSelect = this.container.querySelector('#filter-revenue') as HTMLSelectElement;
    if (revenueSelect) {
      revenueSelect.addEventListener('change', () => {
        this.filter.minRevenue = revenueSelect.value ? parseInt(revenueSelect.value, 10) : undefined;
        this.render();
        this.attachListeners();
      });
    }

    // Competition filter
    const competitionSelect = this.container.querySelector('#filter-competition') as HTMLSelectElement;
    if (competitionSelect) {
      competitionSelect.addEventListener('change', () => {
        this.filter.maxCompetition = (competitionSelect.value as CompetitionLevel) || undefined;
        this.render();
        this.attachListeners();
      });
    }

    // Feasibility filter
    const feasibilitySelect = this.container.querySelector('#filter-feasibility') as HTMLSelectElement;
    if (feasibilitySelect) {
      feasibilitySelect.addEventListener('change', () => {
        this.filter.minFeasibility = feasibilitySelect.value ? parseInt(feasibilitySelect.value, 10) : undefined;
        this.render();
        this.attachListeners();
      });
    }

    // Idea card click → detail view
    this.container.querySelectorAll('[data-idea-id]').forEach((card) => {
      card.addEventListener('click', (e) => {
        // Don't navigate if clicking action buttons
        if ((e.target as HTMLElement).closest('[data-generate-id], [data-dismiss-id], [data-bookmark-id]')) return;
        this.selectedIdeaId = (card as HTMLElement).dataset.ideaId!;
        this.render();
        this.attachListeners();
      });
      card.addEventListener('keydown', (e) => {
        if ((e as KeyboardEvent).key === 'Enter' || (e as KeyboardEvent).key === ' ') {
          e.preventDefault();
          this.selectedIdeaId = (card as HTMLElement).dataset.ideaId!;
          this.render();
          this.attachListeners();
        }
      });
    });

    // Back button
    this.container.querySelector('#pipeline-back')?.addEventListener('click', () => {
      this.selectedIdeaId = null;
      this.render();
      this.attachListeners();
    });

    // Generate buttons
    this.container.querySelectorAll('[data-generate-id]').forEach((btn) => {
      btn.addEventListener('click', (e) => {
        e.stopPropagation();
        const ideaId = (btn as HTMLElement).dataset.generateId!;
        const idea = this.ideas.find((i) => i.id === ideaId);
        if (idea) {
          idea.status = 'generating';
          idea.lastActionAt = new Date().toISOString();
          this.options.onGenerate?.(ideaId);
          this.render();
          this.attachListeners();
        }
      });
    });

    // Dismiss buttons
    this.container.querySelectorAll('[data-dismiss-id]').forEach((btn) => {
      btn.addEventListener('click', (e) => {
        e.stopPropagation();
        const ideaId = (btn as HTMLElement).dataset.dismissId!;
        const idea = this.ideas.find((i) => i.id === ideaId);
        if (idea) {
          idea.status = 'dismissed';
          idea.lastActionAt = new Date().toISOString();
          this.options.onDismiss?.(ideaId);
          if (this.selectedIdeaId === ideaId) {
            this.selectedIdeaId = null;
          }
          this.render();
          this.attachListeners();
        }
      });
    });

    // Bookmark buttons
    this.container.querySelectorAll('[data-bookmark-id]').forEach((btn) => {
      btn.addEventListener('click', (e) => {
        e.stopPropagation();
        const ideaId = (btn as HTMLElement).dataset.bookmarkId!;
        const idea = this.ideas.find((i) => i.id === ideaId);
        if (idea) {
          idea.status = idea.status === 'bookmarked' ? 'pipeline' : 'bookmarked';
          idea.lastActionAt = new Date().toISOString();
          this.options.onBookmark?.(ideaId);
          this.render();
          this.attachListeners();
        }
      });
    });
  }

  // ---------------------------------------------------------------------------
  // Helpers
  // ---------------------------------------------------------------------------

  private getStatusLabel(status: IdeaStatus): string {
    switch (status) {
      case 'pipeline': return 'In Pipeline';
      case 'generating': return 'Generating...';
      case 'generated': return 'Generated';
      case 'published': return 'Published';
      case 'dismissed': return 'Dismissed';
      case 'bookmarked': return '🔖 Bookmarked';
      default: return status;
    }
  }

  private getCompetitionDescription(level: CompetitionLevel): string {
    switch (level) {
      case 'low': return 'Few direct competitors exist. Strong opportunity for first-mover advantage.';
      case 'medium': return 'Several competitors exist but market is not saturated. Differentiation is key.';
      case 'high': return 'Many established competitors. Requires strong differentiation and marketing to succeed.';
    }
  }

  private formatNumber(num: number): string {
    if (num >= 1000000) return `${(num / 1000000).toFixed(1)}M`;
    if (num >= 1000) return `${(num / 1000).toFixed(0)}K`;
    return num.toString();
  }
}
